### ISSUE TITLE
Edit buttons do not respond

### ISSUE THREAD

**Issue by guysoft** [cprasmu/OctoPrint-OrviboS20#3]
The + and edit buttons don't work:
![Screenshot_20190901_134442](https://user-images.githubusercontent.com/325670/64075273-b0963f80-ccbe-11e9-894d-1b42f8517302.png)

Console gives:

```
Could not bind view model orvibos20ViewModel to target #settings_plugin_orvibos20 : TypeError: Unable to process binding "visible: function(){return settings.settings.plugins.tplinksmartplug.arrSmartplugs().length > 0 }"
Message: Cannot read property 'arrSmartplugs' of undefined
    at visible (eval at parseBindingsString (http://pursa.local/static/webassets/packed_libs.js?ea9fbc9a:11374:90), <anonymous>:3:109)
    at update (http://pursa.local/static/webassets/packed_libs.js?ea9fbc9a:11409:229)
    at a.B.i (http://pursa.local/static/webassets/packed_libs.js?ea9fbc9a:11378:286)
    at Function.Pc (http://pursa.local/static/webassets/packed_libs.js?ea9fbc9a:11357:355)
    at Function.Qc (http://pursa.local/static/webassets/packed_libs.js?ea9fbc9a:11357:133)
    at Function.aa (http://pursa.local/static/webassets/packed_libs.js?ea9fbc9a:11356:482)
    at Object.a.m.a.B (http://pursa.local/static/webassets/packed_libs.js?ea9fbc9a:11355:39)
    at http://pursa.local/static/webassets/packed_libs.js?ea9fbc9a:11378:273
    at Object.q (http://pursa.local/static/webassets/packed_libs.js?ea9fbc9a:11317:244)
    at m (http://pursa.local/static/webassets/packed_libs.js?ea9fbc9a:11377:318)
```

**Comment by guysoft** [comment]
Hey,
I am not sure how to fix it, because I need an example for how the config looks like in OctoPrint's yml file. Can you provide that @cprasmu  ?
(I mean an actual file or section as an example. The example in the README does not help me understand where it should be and the exact format to the character).

**Comment by cprasmu** [comment]
@guysoft I will take a look and see if I can remeber !

**Comment by cprasmu** [comment]
I have fixed this it was due to the wrong DIV element in the file orvibos20_settings.jinja2

**Comment by guysoft** [comment]
Works! Thanks!

Note: I can turn the light on and off using gcode. but it will only switch on using the web inderface.
Its likely a web issue, becasuse when turning on I see in the logs:
```
==> /home/pi/.octoprint/logs/plugin_orvibos20_debug.log <==
[2019-09-22 10:08:24,326] DEBUG: Checking status of 172.27.190.xxx.
[2019-09-22 10:08:29,649] DEBUG: Turning on 172.27.190.xxx.
[2019-09-22 10:08:30,890] DEBUG: {'autoConnect': True, 'ip': '172.27.190.xxx', 'btnColor': '#808080', 'autoDisconnectDelay': 0, 'sysCmdOff': False, 'gcodeEnabled': True, 'gcodeOnDelay': 0, 'countdownOnDelay': 0, 'label': 'light', 'warnPrinting': False, 'gcodeOffDelay': 0, 'sysCmdOnDelay': 0, 'countdownOffDelay': 0, 'sysRunCmdOff': '', 'useCountdownRules': False, 'autoDisconnect': True, 'sysRunCmdOn': '', 'icon': 'icon-bolt', 'displayWarning': True, 'autoConnectDelay': 10, 'currentState': 'off', 'sysCmdOn': False, 'sysCmdOffDelay': 0}
[2019-09-22 10:08:32,023] DEBUG: Checking status of 172.27.190.xxx.
```

But no log entry switching off. Nor do i see anything in the console.

If I try resending the turnOn with the command turnOff manually, I get:

```
2019-09-22 10:11:46,810 - octoprint.server.api - ERROR - Error while excuting SimpleApiPlugin orvibos20
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/api/__init__.py", line 100, in pluginCommand
    command, data, response = get_json_command_from_request(request, valid_commands)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/util/flask.py", line 1365, in get_json_command_from_request
    data = request.json
  File "/home/pi/oprint/local/lib/python2.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/wrappers.py", line 108, in json
    return self.get_json()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/wrappers.py", line 145, in get_json
    rv = self.on_json_loading_failed(e)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/wrappers.py", line 162, in on_json_loading_failed
    raise BadRequest()
```

Though gcode works fine.

**Comment by cprasmu** [comment]
do you have warnings turned on- mine also doesn't turn off if the warnings are enabled? I think its due to the modal warning dialog not displaying?

**Comment by cprasmu** [comment]
I also think I might add mac address to the configuration as this will make it way more reliable

**Comment by guysoft** [comment]
Warning is selected in the settings menu. Also I set the javasript console to all debug levels. Tried with both firefox and chromum, same behavor:
It makes the icon spin, but will not switch off, or send the network post request. I can turn it off in the Gcode, then turn it on again with the web inteface button.

**Comment by cprasmu** [comment]
think i have fixed it. the warning dialog was being referred to as OrviboS20Warning and not OrviboS20PlugWarning as it should have been in the javascript. I have committed the change and I'm going to try and reinstall the plugin

**Comment by cprasmu** [comment]
Seems to work !

**Comment by guysoft** [comment]
Confirmed, works here. Thanks!
