### ISSUE TITLE
Getting ERROR - 500 POST when IP has changed

### ISSUE THREAD

**Issue by guysoft** [cprasmu/OctoPrint-OrviboS20#6]
Hey, when pressing the "On" switch on the web UI i get

```
2019-12-01 13:25:22,768 - octoprint.server.api - ERROR - Error while excuting SimpleApiPlugin orvibos20
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/api/__init__.py", line 104, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_orvibos20/__init__.py", line 576, in on_api_command
    self.turn_on("{ip}".format(**data))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_orvibos20/__init__.py", line 498, in turn_on
    d = Orvibo.discover(plugip)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_orvibos20/__init__.py", line 339, in discover
    raise OrviboException('Device ip={} not found in {}.'.format(ip, devices.keys()))
OrviboException: Device ip=172.27.190.91 not found in ['172.27.190.72'].
2019-12-01 13:25:22,791 - tornado.access - ERROR - 500 POST /api/plugin/orvibos20 (172.27.190.206) 1492.11ms
```

In the log:

```
$ cat ~/.octoprint/logs/plugin_orvibos20_debug.log
[2019-12-01 13:22:45,865] DEBUG: Checking status of 172.27.190.91.
[2019-12-01 13:25:21,330] DEBUG: Turning on 172.27.190.91.
```

Seems like the IP changed. Should get a decent massage not a 500 internal server error

**Comment by cprasmu** [comment]
ok thanks I will try and look in to this hopefully soon
