### ISSUE TITLE
Light failes to shut down

### ISSUE THREAD

**Issue by guysoft** [cprasmu/OctoPrint-OrviboS20#7]
In OctoPrint log I get:
```
[2019-12-01 13:35:11,492] DEBUG: Received M81 command, attempting power off of 172.27.190.91.
[2019-12-01 13:35:11,497] DEBUG: None
```

In the log:

```
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 3292, in _process_command_phase
    hook_results = hook(self, phase, command, command_type, gcode, subcode=subcode, tags=tags)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_orvibos20/__init__.py", line 614, in processGCODE
    if plug["gcodeEnabled"]:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Looks like a setting issue in ``plug["gcodeEnabled"]``

**Comment by cprasmu** [comment]
I think the issue stems from a badly formatted Ip address. I can replicate it by adding a . at the end of the switch Ip

**Comment by guysoft** [comment]
Ok, I don't remember what I did and don't have that instance anymore. If you like you can close it and reopen if it come up again.
